# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload Tsubusu to TestFlight"
  lane :beta do
    api_key_path = File.expand_path("~/.config/tsubusu/api_key.json")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      clean: true,
      xcargs: "FLUTTER_BUILD_NAME=1.0.6 FLUTTER_BUILD_NUMBER=2",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        signingCertificate: "Apple Distribution",
        teamID: "PQXW23FNYJ",
        provisioningProfiles: {
          "com.shinyayoshida.tsubusu" => "com.shinyayoshida.tsubusu AppStore"
        }
      },
      output_directory: "../build/ios/ipa",
      output_name: "tsubusu.ipa"
    )

    upload_to_testflight(
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
      api_key_path: api_key_path
    )
  end
end
