name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          architecture: x64

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos --release

      - name: Create macOS DMG
        run: |
          # Create a temporary directory for DMG contents
          mkdir -p dmg_contents
          cp -R build/macos/Build/Products/Release/tsubusu.app dmg_contents/
          
          # Create DMG
          hdiutil create -volname "tsubusu" -srcfolder dmg_contents -ov -format UDZO tsubusu-macos.dmg

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsubusu-macos
          path: tsubusu-macos.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          architecture: x64

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Create Windows ZIP
        run: |
          cd build/windows/x64/runner/Release
          Compress-Archive -Path . -DestinationPath ../../../../../tsubusu-windows.zip
        shell: pwsh

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsubusu-windows
          path: tsubusu-windows.zip

  release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: tsubusu-macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: tsubusu-windows

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tsubusu-macos.dmg
            tsubusu-windows.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}